spring:
  profiles:
    active: local
  application:
    name: oauth2-jwt
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis://127.0.0.1
      port: 6379

jwt:
  secret-key: "*****"
  expiration-mins: 30

server:
  port: 8080
  forward-headers-strategy: framework
